pytorch:
  model_type:
    _target_: src.model.pytorch_model.PTObjectDetectionModel
  depth: 0.33
  width: 0.25
  fine_tune: False
  image_size: ${data_module.dataset.image_size}
  num_classes: ${data_module.dataset.num_classes}
  device: ${device}
